version: 0.2  
### Defines the steps used by AWS CodeBuild  
   
phases:  
  install:   
    runtime-versions:   
      docker: 18  
  pre_build:  
    commands:  
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region ${region} --no-include-email)
      - REPOSITORY_URI=${repository_url}
      - CONTAINER_NAME=${container_name}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Entered the pre_build phase...
  build:  
    commands:  
      - echo Building the Docker image...  
      - docker build -t $REPOSITORY_URI:latest -t $REPOSITORY_URI:$IMAGE_TAG .  
  post_build:  
    commands:  
      - echo Pushing the Docker images to container registry...  
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...  
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo  Build completed on `date`
artifacts:
  files: imagedefinitions.json